import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const interSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin", "vietnamese"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { AIProvider } from "@/components/providers/AIProvider";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="vi"
      className={`${interSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-sans">
        <AIProvider>
          {children}
        </AIProvider>
      </body>
    </html>
  );
}
